### PR TITLE
Add User-Agent to headers.

### LINKED ISSUE #5: User agent required?
Looks like the reddit api wants Meteor to set a user agent. How can this be achieved? Documentation for what can be passed into Meteor's `requestCredential ` method seems pretty sparse.

```
W20150126-16:36:39.719(-6) (oauth_server.js:398) Error in OAuth Server:
Failed to fetch identity from reddit. failed [403]
<!doctype html><html><title>Ow! -- reddit.com</title><style>body{text-align:center;position:absolute;top:50%;margin:0;margin-top:-335px;width:100%}h2,h3{color:#222;font:bold 200%/100px sans-serif;margin:0}h3{color:#777;font:normal 150% sans-serif}</style><img src=//s3.amazonaws.com/redditstatic/youbrokeit3.png alt=""><h2>user agent required</h2><h3>please review our <a href="http://github.com/reddit/reddit/wiki/API">api rules</a>. thanks.
```

### PR DESCRIPTION
**Pull request by albertstartup**
Fixes https://github.com/PandaWhisperer/meteor-accounts-reddit/issues/5

### CODE REVIEW

**Comment by PandaWhisperer** [comment]
Thanks for the fix, @albertstartup.

**Comment by albertstartup** [comment]
no problem

**Comment by davidmh** [comment]
Hey @PandaWhisperer thanks for this package, and @albertstartup for the fix.

@PandaWhisperer could you make a new tag including this change? meteor-accounts-reddit is istill using 0.0.6, which doesn't have this fix yet.

**Comment by bearcott** [comment]
plz

**Pull request merged**
